import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import Anthropic from "@anthropic-ai/sdk";

export async function POST() {
  try {
    const session = await auth();
    if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const role = (session.user as any).role;
    if (role !== "ADMIN" && role !== "SUPERADMIN") {
      return NextResponse.json({ error: "Yetkisiz" }, { status: 403 });
    }
    const clinicId = (session.user as any).clinicId;
    if (!clinicId) return NextResponse.json({ error: "No clinic" }, { status: 400 });

    const anthropic = new Anthropic();

    const today = new Date();
    const weekStart = new Date(today);
    weekStart.setDate(today.getDate() - today.getDay() + 1);

    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 2000,
      messages: [{
        role: "user",
        content: `Poby.ai (işletmeler için AI destekli yönetim platformu) için bu hafta paylaşılacak 7 tweet üret.

Kurallar:
- Her tweet Türkçe ve max 280 karakter
- Her gün için 1 tweet (Pazartesi-Pazar)
- Konular: işletme yönetimi, dijitalleşme, müşteri ilişkileri, finans takibi, stok yönetimi, randevu sistemi, AI teknolojisi
- Emoji kullan ama abartma
- CTA olarak poby.ai veya poby.ai/register kullan
- Hashtag'ler ekle

JSON array olarak döndür, her eleman:
{"content": "tweet metni", "occasion": "kısa açıklama", "day": "2026-04-07"}

Haftanın başlangıç tarihi: ${weekStart.toISOString().split("T")[0]}

Sadece JSON array döndür, başka açıklama yapma.`,
      }],
    });

    const text = (response.content[0] as any).text;
    let tweets: Array<{ content: string; occasion: string; day: string }>;

    try {
      // Extract JSON from response
      const jsonMatch = text.match(/\[[\s\S]*\]/);
      tweets = jsonMatch ? JSON.parse(jsonMatch[0]) : [];
    } catch {
      return NextResponse.json({ error: "AI yanıtı parse edilemedi" }, { status: 500 });
    }

    let created = 0;
    for (const tweet of tweets) {
      await prisma.scheduledPost.create({
        data: {
          clinicId,
          type: "tweet",
          platform: "twitter",
          content: tweet.content,
          scheduledAt: new Date(`${tweet.day}T10:00:00`),
          status: "DRAFT",
          occasion: tweet.occasion || null,
          isAutoGenerated: true,
        },
      });
      created++;
    }

    return NextResponse.json({ success: true, created });
  } catch (error) {
    console.error("AI generate error:", error);
    return NextResponse.json({ error: "AI içerik üretimi başarısız" }, { status: 500 });
  }
}
