import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: "Yetkisiz" }, { status: 401 });
    }
    const clinicId = (session.user as any).clinicId;
    if (!clinicId) {
      return NextResponse.json({ error: "Klinik bulunamadı" }, { status: 400 });
    }

    const posts = await prisma.scheduledPost.findMany({
      where: { clinicId },
      orderBy: { scheduledAt: "asc" },
    });

    return NextResponse.json(posts);
  } catch (error) {
    console.error("Get posts error:", error);
    return NextResponse.json({ error: "Paylaşımlar alınamadı" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: "Yetkisiz" }, { status: 401 });
    }
    const clinicId = (session.user as any).clinicId;
    if (!clinicId) {
      return NextResponse.json({ error: "Klinik bulunamadı" }, { status: 400 });
    }

    const { type, platform, content, imageUrl, scheduledAt, isAutoGenerated, occasion } = await req.json();

    if (!platform || !scheduledAt) {
      return NextResponse.json({ error: "Platform ve tarih gerekli" }, { status: 400 });
    }

    const post = await prisma.scheduledPost.create({
      data: {
        clinicId,
        type: type || "post",
        platform,
        content: content || null,
        imageUrl: imageUrl || null,
        scheduledAt: new Date(scheduledAt),
        isAutoGenerated: isAutoGenerated || false,
        occasion: occasion || null,
      },
    });

    return NextResponse.json(post, { status: 201 });
  } catch (error) {
    console.error("Create post error:", error);
    return NextResponse.json({ error: "Paylaşım oluşturulamadı" }, { status: 500 });
  }
}
