"use client";

import { useEffect, useState, useRef } from "react";
import {
  Plus, Send, Trash2, Check, Clock, AlertCircle, Twitter,
  Edit, Calendar, Sparkles, Loader2, X, ImagePlus, Eye,
  ThumbsDown, BarChart3, RefreshCw, Zap, Upload, Wand2,
  RotateCcw, Film, FileText, Image as LucideImage, MessageSquare,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";

interface Post {
  id: string;
  type: string;
  platform: string;
  content: string | null;
  threadContent: string | null;
  imageUrl: string | null;
  scheduledAt: string;
  postedAt: string | null;
  status: string;
  occasion: string | null;
  externalPostId: string | null;
  errorMessage: string | null;
  feedback: string | null;
  impressions: number | null;
  likes: number | null;
  replies: number | null;
  retweets: number | null;
  isAutoGenerated: boolean;
  mediaSuggestion: string | null;
  mediaSuggestionReason: string | null;
  createdAt: string;
}

interface Concept {
  title: string;
  description: string;
  prompt: string;
}

const STATUS_CONFIG: Record<string, { label: string; color: string; icon: any }> = {
  DRAFT: { label: "Taslak", color: "bg-gray-100 text-gray-700", icon: Edit },
  APPROVED: { label: "Onaylı", color: "bg-blue-100 text-blue-700", icon: Check },
  SCHEDULED: { label: "Zamanlandı", color: "bg-purple-100 text-purple-700", icon: Clock },
  POSTED: { label: "Paylaşıldı", color: "bg-emerald-100 text-emerald-700", icon: Check },
  FAILED: { label: "Hata", color: "bg-red-100 text-red-700", icon: AlertCircle },
  CANCELLED: { label: "İptal", color: "bg-gray-100 text-gray-500", icon: AlertCircle },
};

const TYPE_LABELS: Record<string, string> = { tweet: "Tweet", thread: "Thread", poll: "Anket" };
const DAYS = ["Pzr", "Pzt", "Sal", "Çar", "Per", "Cum", "Cmt"];

// Format date to Istanbul timezone display
function formatIstanbul(dateStr: string) {
  return new Date(dateStr).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });
}

export default function AdminMarketingPage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState("all");
  const [showCreate, setShowCreate] = useState(false);
  const [publishing, setPublishing] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [selectedPost, setSelectedPost] = useState<Post | null>(null);
  const [fixing, setFixing] = useState(false);
  const [feedbackText, setFeedbackText] = useState("");

  // Create form
  const [form, setForm] = useState({
    type: "tweet",
    platform: "twitter",
    content: "",
    threadPosts: [""],
    scheduledAt: "",
    occasion: "",
  });
  const [saving, setSaving] = useState(false);

  // Edit state in detail modal
  const [editContent, setEditContent] = useState("");
  const [editThreadContent, setEditThreadContent] = useState<string[]>([]);
  const [editScheduledAt, setEditScheduledAt] = useState("");
  const [editOccasion, setEditOccasion] = useState("");
  const [editSaving, setEditSaving] = useState(false);

  // Image upload & AI generation
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [imageMode, setImageMode] = useState<"none" | "ai" | "upload">("none");
  // Concept flow states
  const [aiStep, setAiStep] = useState<"concepts" | "generate" | "results">("concepts");
  const [concepts, setConcepts] = useState<Concept[]>([]);
  const [loadingConcepts, setLoadingConcepts] = useState(false);
  const [selectedConcept, setSelectedConcept] = useState<Concept | null>(null);
  const [conceptEdit, setConceptEdit] = useState("");
  const [aiImageModel, setAiImageModel] = useState<"flux-schnell" | "flux-pro">("flux-schnell");
  const [aiImageAspect, setAiImageAspect] = useState<"16:9" | "1:1" | "9:16">("16:9");
  const [aiImageCount, setAiImageCount] = useState<1 | 2 | 3>(1);
  const [aiGenerating, setAiGenerating] = useState(false);
  const [aiGeneratedImages, setAiGeneratedImages] = useState<{ url: string; id: string }[]>([]);
  const [feedbackMode, setFeedbackMode] = useState(false);
  const [imageFeedback, setImageFeedback] = useState("");
  // Lightbox
  const [lightboxUrl, setLightboxUrl] = useState<string | null>(null);

  // Metrics edit
  const [showMetrics, setShowMetrics] = useState(false);
  const [metrics, setMetrics] = useState({ impressions: "", likes: "", replies: "", retweets: "" });

  useEffect(() => { fetchPosts(); }, []);

  async function fetchPosts() {
    try {
      const res = await fetch("/api/admin/marketing");
      if (res.ok) {
        const data = await res.json();
        setPosts(data.posts || []);
      }
    } catch {} finally { setLoading(false); }
  }

  async function handleCreate() {
    setSaving(true);
    try {
      const body: any = {
        type: form.type,
        platform: form.platform,
        content: form.type === "thread" ? form.threadPosts[0] : form.content,
        scheduledAt: form.scheduledAt || new Date().toISOString(),
        occasion: form.occasion || undefined,
      };
      if (form.type === "thread") {
        body.threadContent = form.threadPosts.filter(t => t.trim());
      }
      const res = await fetch("/api/admin/marketing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (res.ok) {
        await fetchPosts();
        setShowCreate(false);
        setForm({ type: "tweet", platform: "twitter", content: "", threadPosts: [""], scheduledAt: "", occasion: "" });
      }
    } catch {} finally { setSaving(false); }
  }

  async function updatePost(id: string, data: any) {
    await fetch("/api/admin/marketing", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, ...data }),
    });
    await fetchPosts();
  }

  async function handlePublish(id: string) {
    setPublishing(id);
    try {
      const res = await fetch("/api/admin/marketing/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      const data = await res.json();
      if (!res.ok) alert(`Hata: ${data.error || "Bilinmeyen hata"}`);
      await fetchPosts();
      // Refresh selected post
      if (selectedPost?.id === id) {
        const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === id);
        if (updated) setSelectedPost(updated);
      }
    } catch {} finally { setPublishing(null); }
  }

  async function handleDelete(id: string) {
    if (!confirm("Bu içeriği silmek istediğinize emin misiniz?")) return;
    await fetch("/api/admin/marketing", {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id }),
    });
    setSelectedPost(null);
    fetchPosts();
  }

  async function handleFix(post: Post) {
    if (!feedbackText.trim()) return;
    setFixing(true);
    try {
      const res = await fetch("/api/admin/marketing/fix-content", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: post.id, feedback: feedbackText }),
      });
      if (res.ok) {
        setFeedbackText("");
        await fetchPosts();
        const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === post.id);
        if (updated) setSelectedPost(updated);
      } else {
        const data = await res.json();
        alert(`Hata: ${data.error}`);
      }
    } catch {} finally { setFixing(false); }
  }

  async function handleImageUpload(postId: string, file: File) {
    setUploading(true);
    try {
      const formData = new FormData();
      formData.append("file", file);
      const res = await fetch("/api/admin/marketing/upload", { method: "POST", body: formData });
      if (res.ok) {
        const { imageUrl } = await res.json();
        await updatePost(postId, { imageUrl });
        const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === postId);
        if (updated) setSelectedPost(updated);
      }
    } catch {} finally { setUploading(false); }
  }

  async function handleSuggestConcepts(post: Post) {
    const content = post.content || (post.threadContent ? JSON.parse(post.threadContent)[0] : "");
    if (!content) return;
    setLoadingConcepts(true);
    setConcepts([]);
    setSelectedConcept(null);
    setAiStep("concepts");
    try {
      const res = await fetch("/api/marketing/ai-studio/suggest-concepts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setConcepts(data.concepts || []);
    } catch (err) {
      alert(err instanceof Error ? err.message : "Konsept önerisi başarısız");
    } finally {
      setLoadingConcepts(false);
    }
  }

  function handlePickConcept(concept: Concept) {
    setSelectedConcept(concept);
    setConceptEdit(concept.prompt);
    setAiStep("generate");
    setAiGeneratedImages([]);
    setFeedbackMode(false);
    setImageFeedback("");
  }

  async function handleAiImageGenerate() {
    const prompt = conceptEdit.trim() || selectedConcept?.prompt;
    if (!prompt) return;
    setAiGenerating(true);
    setAiGeneratedImages([]);
    setAiStep("results");
    try {
      const results: { url: string; id: string }[] = [];
      const promises = Array.from({ length: aiImageCount }, () =>
        fetch("/api/marketing/ai-studio/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            prompt,
            model: aiImageModel,
            aspectRatio: aiImageAspect,
          }),
        }).then(r => r.json())
      );
      const responses = await Promise.all(promises);
      for (const data of responses) {
        if (data.imageUrl) results.push({ url: data.imageUrl, id: data.id });
      }
      if (results.length === 0) throw new Error("Görsel üretilemedi");
      setAiGeneratedImages(results);
    } catch (err) {
      alert(err instanceof Error ? err.message : "Görsel üretimi başarısız");
    } finally {
      setAiGenerating(false);
    }
  }

  async function handleRegenerateWithFeedback() {
    if (!imageFeedback.trim() || !selectedConcept) return;
    setAiGenerating(true);
    try {
      const res = await fetch("/api/marketing/ai-studio/refine-concept", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          originalPrompt: conceptEdit || selectedConcept.prompt,
          feedback: imageFeedback,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setConceptEdit(data.prompt);
      setFeedbackMode(false);
      setImageFeedback("");
      // Auto-generate with refined prompt
      setAiGeneratedImages([]);
      const results: { url: string; id: string }[] = [];
      const promises = Array.from({ length: aiImageCount }, () =>
        fetch("/api/marketing/ai-studio/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            prompt: data.prompt,
            model: aiImageModel,
            aspectRatio: aiImageAspect,
          }),
        }).then(r => r.json())
      );
      const responses = await Promise.all(promises);
      for (const d of responses) {
        if (d.imageUrl) results.push({ url: d.imageUrl, id: d.id });
      }
      setAiGeneratedImages(results);
    } catch (err) {
      alert(err instanceof Error ? err.message : "Düzenleme başarısız");
    } finally {
      setAiGenerating(false);
    }
  }

  async function handleSelectAiImage(postId: string, imageUrl: string) {
    await updatePost(postId, { imageUrl });
    const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === postId);
    if (updated) setSelectedPost(updated);
    setAiGeneratedImages([]);
    setImageMode("none");
    setAiStep("concepts");
  }

  function openImageAiPanel(post: Post) {
    setImageMode("ai");
    setAiStep("concepts");
    setConcepts([]);
    setSelectedConcept(null);
    setAiGeneratedImages([]);
    setFeedbackMode(false);
    setImageFeedback("");
    handleSuggestConcepts(post);
  }

  async function handleSaveEdit() {
    if (!selectedPost) return;
    setEditSaving(true);
    try {
      const data: any = {
        content: editContent,
        scheduledAt: editScheduledAt,
        occasion: editOccasion,
      };
      if (selectedPost.type === "thread") {
        data.threadContent = editThreadContent.filter(t => t.trim());
        data.content = editThreadContent[0] || editContent;
      }
      await updatePost(selectedPost.id, data);
      const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id);
      if (updated) setSelectedPost(updated);
    } catch {} finally { setEditSaving(false); }
  }

  async function handleSaveMetrics() {
    if (!selectedPost) return;
    await updatePost(selectedPost.id, {
      impressions: metrics.impressions ? Number(metrics.impressions) : null,
      likes: metrics.likes ? Number(metrics.likes) : null,
      replies: metrics.replies ? Number(metrics.replies) : null,
      retweets: metrics.retweets ? Number(metrics.retweets) : null,
    });
    const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id);
    if (updated) setSelectedPost(updated);
    setShowMetrics(false);
  }

  function openDetailModal(post: Post) {
    setSelectedPost(post);
    setEditContent(post.content || "");
    setEditThreadContent(post.threadContent ? JSON.parse(post.threadContent) : []);
    setEditScheduledAt(new Date(post.scheduledAt).toLocaleString("sv-SE", { timeZone: "Europe/Istanbul" }).replace(" ", "T").slice(0, 16));
    setEditOccasion(post.occasion || "");
    setFeedbackText("");
    setImageMode("none");
    setAiStep("concepts");
    setConcepts([]);
    setSelectedConcept(null);
    setAiGeneratedImages([]);
    setFeedbackMode(false);
    setImageFeedback("");
    setShowMetrics(false);
    setMetrics({
      impressions: String(post.impressions || ""),
      likes: String(post.likes || ""),
      replies: String(post.replies || ""),
      retweets: String(post.retweets || ""),
    });
  }

  const filteredPosts = tab === "all" ? posts : posts.filter(p => p.status === tab.toUpperCase());

  // Weekly calendar
  const today = new Date();
  const startOfWeek = new Date(today);
  startOfWeek.setDate(today.getDate() - today.getDay() + 1);
  const weekDays = Array.from({ length: 7 }, (_, i) => {
    const d = new Date(startOfWeek);
    d.setDate(startOfWeek.getDate() + i);
    return d;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-bold text-gray-900">Content Studio</h1>
          <p className="text-xs text-gray-500">İçerik oluştur, zamanla, paylaş</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={async () => {
            setGenerating(true);
            const res = await fetch("/api/admin/marketing/generate-weekly", { method: "POST" });
            const data = await res.json();
            if (res.ok) alert(`${data.created} içerik oluşturuldu! (${data.week})`);
            else alert(`Hata: ${data.error}`);
            await fetchPosts();
            setGenerating(false);
          }} disabled={generating}>
            {generating ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1 h-3.5 w-3.5" />}
            Haftalık Üret
          </Button>
          <Button onClick={() => setShowCreate(true)} size="sm">
            <Plus className="mr-1 h-3.5 w-3.5" /> Oluştur
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
        {[
          { label: "Taslak", count: posts.filter(p => p.status === "DRAFT").length, color: "text-gray-600" },
          { label: "Onaylı", count: posts.filter(p => p.status === "APPROVED").length, color: "text-blue-600" },
          { label: "Zamanlandı", count: posts.filter(p => p.status === "SCHEDULED").length, color: "text-purple-600" },
          { label: "Paylaşıldı", count: posts.filter(p => p.status === "POSTED").length, color: "text-emerald-600" },
          { label: "Hata", count: posts.filter(p => p.status === "FAILED").length, color: "text-red-600" },
        ].map(s => (
          <Card key={s.label}>
            <CardContent className="p-3 text-center">
              <p className="text-[10px] text-gray-400 uppercase">{s.label}</p>
              <p className={`text-lg font-bold ${s.color}`}>{s.count}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Weekly Calendar */}
      <Card>
        <CardHeader className="py-3 px-4">
          <CardTitle className="text-sm">Haftalık Takvim</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="grid grid-cols-7 border-t">
            {weekDays.map((day, i) => {
              const dayStr = day.toISOString().split("T")[0];
              const dayPosts = posts.filter(p => {
                const pDate = new Date(p.scheduledAt).toLocaleDateString("sv-SE", { timeZone: "Europe/Istanbul" });
                return pDate === dayStr;
              });
              const isToday = dayStr === today.toISOString().split("T")[0];
              return (
                <div key={i} className={`border-r last:border-0 p-2 min-h-[80px] ${isToday ? "bg-[#EEF2FF]/30" : ""}`}>
                  <p className={`text-[10px] font-semibold ${isToday ? "text-[#4F46E5]" : "text-gray-400"}`}>
                    {DAYS[day.getDay()]} {day.getDate()}
                  </p>
                  <div className="mt-1 space-y-1">
                    {dayPosts.map(p => {
                      const cfg = STATUS_CONFIG[p.status] || STATUS_CONFIG.DRAFT;
                      return (
                        <div
                          key={p.id}
                          onClick={() => openDetailModal(p)}
                          className={`rounded px-1.5 py-0.5 text-[9px] font-medium truncate cursor-pointer hover:ring-1 hover:ring-indigo-300 ${cfg.color}`}
                        >
                          {p.mediaSuggestion === "image" && !p.imageUrl ? "🖼️" : p.mediaSuggestion === "video" ? "🎬" : ""}{p.imageUrl ? "📎" : ""} {p.content?.slice(0, 20) || "Thread"}
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Content List */}
      <Tabs value={tab} onValueChange={setTab}>
        <div className="overflow-x-auto">
          <TabsList className="w-max sm:w-auto">
            <TabsTrigger value="all" className="text-xs">Tümü ({posts.length})</TabsTrigger>
            <TabsTrigger value="draft" className="text-xs">Taslak</TabsTrigger>
            <TabsTrigger value="approved" className="text-xs">Onaylı</TabsTrigger>
            <TabsTrigger value="posted" className="text-xs">Paylaşıldı</TabsTrigger>
            <TabsTrigger value="failed" className="text-xs">Hata</TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value={tab}>
          {loading ? (
            <p className="text-sm text-gray-400 py-8 text-center">Yükleniyor...</p>
          ) : filteredPosts.length === 0 ? (
            <div className="py-12 text-center">
              <Calendar className="mx-auto mb-3 h-8 w-8 text-gray-300" />
              <p className="text-sm text-gray-500">Henüz içerik yok</p>
              <Button size="sm" variant="outline" className="mt-3" onClick={() => setShowCreate(true)}>
                <Plus className="mr-1 h-3 w-3" /> İlk İçeriği Oluştur
              </Button>
            </div>
          ) : (
            <div className="space-y-2">
              {filteredPosts.map(post => {
                const cfg = STATUS_CONFIG[post.status] || STATUS_CONFIG.DRAFT;
                const StatusIcon = cfg.icon;
                return (
                  <Card key={post.id} className="cursor-pointer hover:ring-1 hover:ring-indigo-200 transition-all" onClick={() => openDetailModal(post)}>
                    <CardContent className="p-3">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                            <Twitter className="h-3.5 w-3.5 text-gray-400" />
                            <span className="text-[10px] font-medium text-gray-500 uppercase">{TYPE_LABELS[post.type] || post.type}</span>
                            <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${cfg.color}`}>
                              <StatusIcon className="h-2.5 w-2.5" /> {cfg.label}
                            </span>
                            {post.imageUrl && <ImagePlus className="h-3 w-3 text-indigo-400" />}
                            {!post.imageUrl && post.mediaSuggestion === "image" && (
                              <span className="inline-flex items-center gap-0.5 rounded bg-purple-50 px-1 py-0.5 text-[9px] font-medium text-purple-600" title={post.mediaSuggestionReason || ""}>
                                <LucideImage className="h-2.5 w-2.5" /> Görsel
                              </span>
                            )}
                            {post.mediaSuggestion === "video" && (
                              <span className="inline-flex items-center gap-0.5 rounded bg-amber-50 px-1 py-0.5 text-[9px] font-medium text-amber-600" title={post.mediaSuggestionReason || ""}>
                                <Film className="h-2.5 w-2.5" /> Video
                              </span>
                            )}
                            {post.mediaSuggestion === "none" && (
                              <span className="inline-flex items-center gap-0.5 rounded bg-gray-50 px-1 py-0.5 text-[9px] font-medium text-gray-400" title={post.mediaSuggestionReason || ""}>
                                <FileText className="h-2.5 w-2.5" /> Metin
                              </span>
                            )}
                            {post.isAutoGenerated && <Zap className="h-3 w-3 text-amber-400" />}
                          </div>
                          <p className="text-sm text-gray-800 whitespace-pre-wrap line-clamp-2">
                            {post.content || (post.threadContent ? `Thread (${JSON.parse(post.threadContent).length} tweet)` : "—")}
                          </p>
                          <div className="flex items-center gap-3 mt-1.5 text-[10px] text-gray-400">
                            <span>{formatIstanbul(post.scheduledAt)}</span>
                            {post.occasion && <span>· {post.occasion}</span>}
                            {post.likes != null && (
                              <span className="text-indigo-500">· {post.likes} like · {post.retweets} RT</span>
                            )}
                          </div>
                        </div>
                        <div className="flex items-center gap-1 shrink-0" onClick={e => e.stopPropagation()}>
                          {post.status === "DRAFT" && (
                            <>
                              <button onClick={() => updatePost(post.id, { status: "APPROVED" })} className="rounded-lg bg-blue-50 p-1.5 text-blue-600 hover:bg-blue-100" title="Onayla">
                                <Check className="h-3.5 w-3.5" />
                              </button>
                              <button onClick={async () => { await updatePost(post.id, { status: "APPROVED" }); handlePublish(post.id); }} disabled={publishing === post.id} className="rounded-lg bg-emerald-50 p-1.5 text-emerald-600 hover:bg-emerald-100 disabled:opacity-50" title="Onayla & Paylaş">
                                <Send className="h-3.5 w-3.5" />
                              </button>
                            </>
                          )}
                          {(post.status === "APPROVED" || post.status === "SCHEDULED") && (
                            <button onClick={() => handlePublish(post.id)} disabled={publishing === post.id} className="rounded-lg bg-emerald-50 p-1.5 text-emerald-600 hover:bg-emerald-100 disabled:opacity-50" title="Şimdi Paylaş">
                              <Send className="h-3.5 w-3.5" />
                            </button>
                          )}
                          <button onClick={() => handleDelete(post.id)} className="rounded-lg p-1.5 text-gray-400 hover:bg-red-50 hover:text-red-500" title="Sil">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* ====== DETAIL MODAL ====== */}
      {selectedPost && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setSelectedPost(null)}>
          <div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Twitter className="h-4 w-4 text-gray-400" />
                <span className="text-xs font-medium text-gray-500 uppercase">{TYPE_LABELS[selectedPost.type] || selectedPost.type}</span>
                {(() => {
                  const cfg = STATUS_CONFIG[selectedPost.status] || STATUS_CONFIG.DRAFT;
                  const Icon = cfg.icon;
                  return (
                    <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${cfg.color}`}>
                      <Icon className="h-2.5 w-2.5" /> {cfg.label}
                    </span>
                  );
                })()}
              </div>
              <button onClick={() => setSelectedPost(null)} className="rounded-lg p-1.5 hover:bg-gray-100">
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Content Edit */}
            <div className="space-y-4">
              {selectedPost.type === "thread" ? (
                <div className="space-y-2">
                  <Label className="text-xs font-medium">Thread İçerikleri</Label>
                  {editThreadContent.map((t, i) => (
                    <div key={i} className="flex gap-2">
                      <span className="text-xs text-gray-400 pt-2 shrink-0">{i + 1}/</span>
                      <div className="flex-1">
                        <textarea
                          value={t}
                          onChange={e => {
                            const updated = [...editThreadContent];
                            updated[i] = e.target.value;
                            setEditThreadContent(updated);
                          }}
                          rows={2}
                          className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400"
                          maxLength={280}
                        />
                        <p className="text-right text-[10px] text-gray-400">{t.length}/280</p>
                      </div>
                    </div>
                  ))}
                  <button onClick={() => setEditThreadContent([...editThreadContent, ""])} className="text-xs text-indigo-600 hover:underline">+ Tweet Ekle</button>
                </div>
              ) : (
                <div>
                  <Label className="text-xs font-medium">İçerik</Label>
                  <textarea
                    value={editContent}
                    onChange={e => setEditContent(e.target.value)}
                    rows={4}
                    className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400"
                    maxLength={280}
                  />
                  <p className="text-right text-[10px] text-gray-400">{editContent.length}/280</p>
                </div>
              )}

              {/* Image */}
              <div>
                <div className="flex items-center gap-2">
                  <Label className="text-xs font-medium">Görsel</Label>
                  {selectedPost.mediaSuggestion && !selectedPost.imageUrl && (
                    <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium ${
                      selectedPost.mediaSuggestion === "image" ? "bg-purple-50 text-purple-600" :
                      selectedPost.mediaSuggestion === "video" ? "bg-amber-50 text-amber-600" : "bg-gray-50 text-gray-400"
                    }`} title={selectedPost.mediaSuggestionReason || ""}>
                      {selectedPost.mediaSuggestion === "image" && <><LucideImage className="h-3 w-3" /> Görsel öneriliyor</>}
                      {selectedPost.mediaSuggestion === "video" && <><Film className="h-3 w-3" /> Video öneriliyor</>}
                      {selectedPost.mediaSuggestion === "none" && <><FileText className="h-3 w-3" /> Metin yeterli</>}
                    </span>
                  )}
                </div>
                {selectedPost.mediaSuggestionReason && !selectedPost.imageUrl && (
                  <p className="text-[10px] text-gray-400 mt-0.5 italic">{selectedPost.mediaSuggestionReason}</p>
                )}
                {/* Current image preview */}
                {selectedPost.imageUrl && (
                  <div className="mt-1 mb-2 relative inline-block">
                    <img src={selectedPost.imageUrl} alt="" className="h-24 rounded-lg object-cover border" />
                    <button
                      onClick={async () => { await updatePost(selectedPost.id, { imageUrl: null }); const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id); if (updated) setSelectedPost(updated); }}
                      className="absolute -top-1 -right-1 rounded-full bg-red-500 p-0.5 text-white"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </div>
                )}

                {/* Two option buttons */}
                {imageMode === "none" && (
                  <div className="mt-1 flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => openImageAiPanel(selectedPost)}>
                      <Wand2 className="mr-1 h-3.5 w-3.5 text-purple-500" />
                      AI ile Üret
                    </Button>
                    <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={e => {
                      const file = e.target.files?.[0];
                      if (file && selectedPost) handleImageUpload(selectedPost.id, file);
                    }} />
                    <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()} disabled={uploading}>
                      {uploading ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Upload className="mr-1 h-3.5 w-3.5" />}
                      Dosya Yükle
                    </Button>
                  </div>
                )}

                {/* AI Generation Panel — Concept Flow */}
                {imageMode === "ai" && (
                  <div className="mt-2 rounded-xl border border-purple-200 bg-purple-50/50 p-4 space-y-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-1.5">
                        <Wand2 className="h-3.5 w-3.5 text-purple-600" />
                        <span className="text-xs font-semibold text-purple-800">AI ile Görsel Üret</span>
                        <span className="text-[10px] text-purple-400">
                          {aiStep === "concepts" && "1/3 Konsept"}
                          {aiStep === "generate" && "2/3 Ayarlar"}
                          {aiStep === "results" && "3/3 Sonuç"}
                        </span>
                      </div>
                      <button onClick={() => { setImageMode("none"); setAiStep("concepts"); setAiGeneratedImages([]); }} className="rounded p-1 hover:bg-purple-100">
                        <X className="h-3.5 w-3.5 text-purple-400" />
                      </button>
                    </div>

                    {/* Step 1: Concept suggestions */}
                    {aiStep === "concepts" && (
                      <>
                        {loadingConcepts ? (
                          <div className="flex items-center justify-center py-6">
                            <Loader2 className="h-5 w-5 animate-spin text-purple-500 mr-2" />
                            <span className="text-xs text-purple-600">Konseptler hazırlanıyor...</span>
                          </div>
                        ) : concepts.length > 0 ? (
                          <div className="space-y-2">
                            <p className="text-[11px] text-gray-500">Bir konsept seçin veya düzenleyin:</p>
                            {concepts.map((c, i) => (
                              <button
                                key={i}
                                onClick={() => handlePickConcept(c)}
                                className="w-full text-left rounded-lg border border-gray-200 bg-white p-3 hover:border-purple-400 hover:ring-1 hover:ring-purple-200 transition-all"
                              >
                                <p className="text-xs font-semibold text-gray-900">{c.title}</p>
                                <p className="text-[11px] text-gray-500 mt-0.5">{c.description}</p>
                              </button>
                            ))}
                          </div>
                        ) : (
                          <p className="text-xs text-gray-400 text-center py-4">Konsept önerisi yok</p>
                        )}
                      </>
                    )}

                    {/* Step 2: Settings & generate */}
                    {aiStep === "generate" && selectedConcept && (
                      <>
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <label className="text-[11px] font-medium text-gray-600">Seçilen Konsept</label>
                            <button onClick={() => { setAiStep("concepts"); setSelectedConcept(null); }} className="text-[10px] text-purple-600 hover:underline">Değiştir</button>
                          </div>
                          <p className="text-xs font-medium text-gray-800 mb-1">{selectedConcept.title}</p>
                          <textarea
                            value={conceptEdit}
                            onChange={e => setConceptEdit(e.target.value)}
                            rows={2}
                            className="w-full rounded-lg border border-purple-200 bg-white px-3 py-2 text-[11px] text-gray-600 focus:ring-2 focus:ring-purple-300 focus:border-purple-400"
                            placeholder="Prompt'u düzenleyebilirsiniz..."
                          />
                        </div>

                        <div className="grid grid-cols-3 gap-2">
                          <div>
                            <label className="text-[10px] font-medium text-gray-500">Kalite</label>
                            <select value={aiImageModel} onChange={e => setAiImageModel(e.target.value as any)} className="mt-0.5 w-full rounded-lg border border-gray-200 bg-white px-2 py-1.5 text-xs">
                              <option value="flux-schnell">Hızlı Önizleme</option>
                              <option value="flux-pro">Yüksek Kalite</option>
                            </select>
                          </div>
                          <div>
                            <label className="text-[10px] font-medium text-gray-500">Boyut</label>
                            <select value={aiImageAspect} onChange={e => setAiImageAspect(e.target.value as any)} className="mt-0.5 w-full rounded-lg border border-gray-200 bg-white px-2 py-1.5 text-xs">
                              <option value="16:9">16:9 (X)</option>
                              <option value="1:1">1:1 (Kare)</option>
                              <option value="9:16">9:16 (Dikey)</option>
                            </select>
                          </div>
                          <div>
                            <label className="text-[10px] font-medium text-gray-500">Varyasyon</label>
                            <select value={aiImageCount} onChange={e => setAiImageCount(Number(e.target.value) as any)} className="mt-0.5 w-full rounded-lg border border-gray-200 bg-white px-2 py-1.5 text-xs">
                              <option value={1}>1</option>
                              <option value={2}>2</option>
                              <option value={3}>3</option>
                            </select>
                          </div>
                        </div>

                        <Button onClick={handleAiImageGenerate} disabled={aiGenerating} size="sm" className="w-full bg-purple-600 hover:bg-purple-700">
                          {aiGenerating ? <><Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> Üretiliyor...</> : <><Sparkles className="mr-1 h-3.5 w-3.5" /> Üret</>}
                        </Button>
                      </>
                    )}

                    {/* Step 3: Results */}
                    {aiStep === "results" && (
                      <>
                        {aiGenerating ? (
                          <div className="flex items-center justify-center py-8">
                            <Loader2 className="h-5 w-5 animate-spin text-purple-500 mr-2" />
                            <span className="text-xs text-purple-600">Görseller üretiliyor...</span>
                          </div>
                        ) : aiGeneratedImages.length > 0 ? (
                          <div className="space-y-3">
                            <p className="text-[11px] font-medium text-gray-600">{aiGeneratedImages.length} görsel — tıklayarak seçin, büyütmek için sağ tık:</p>
                            <div className={`grid gap-2 ${aiGeneratedImages.length === 1 ? "grid-cols-1" : aiGeneratedImages.length === 2 ? "grid-cols-2" : "grid-cols-3"}`}>
                              {aiGeneratedImages.map((img, i) => (
                                <div key={i} className="group relative rounded-lg overflow-hidden border border-gray-200 cursor-pointer hover:ring-2 hover:ring-purple-400 transition-all">
                                  <img
                                    src={img.url}
                                    alt={`Varyasyon ${i + 1}`}
                                    className="w-full aspect-video object-cover"
                                    onClick={() => handleSelectAiImage(selectedPost.id, img.url)}
                                    onContextMenu={e => { e.preventDefault(); setLightboxUrl(img.url); }}
                                  />
                                  <div className="absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-colors flex items-center justify-center pointer-events-none">
                                    <span className="text-white text-xs font-semibold opacity-0 group-hover:opacity-100 transition-opacity">Seç</span>
                                  </div>
                                  {/* Lightbox trigger */}
                                  <button
                                    onClick={e => { e.stopPropagation(); setLightboxUrl(img.url); }}
                                    className="absolute top-1 right-1 rounded bg-black/40 p-1 text-white opacity-0 group-hover:opacity-100 transition-opacity"
                                  >
                                    <Eye className="h-3 w-3" />
                                  </button>
                                </div>
                              ))}
                            </div>

                            {/* Regenerate options */}
                            <div className="flex gap-2">
                              <Button variant="outline" size="sm" className="flex-1" onClick={handleAiImageGenerate} disabled={aiGenerating}>
                                <RotateCcw className="mr-1 h-3.5 w-3.5" /> Yeniden üret
                              </Button>
                              <Button variant="outline" size="sm" className="flex-1" onClick={() => setFeedbackMode(!feedbackMode)}>
                                <MessageSquare className="mr-1 h-3.5 w-3.5" /> Feedback ile düzelt
                              </Button>
                            </div>

                            {feedbackMode && (
                              <div className="space-y-2">
                                <textarea
                                  value={imageFeedback}
                                  onChange={e => setImageFeedback(e.target.value)}
                                  rows={2}
                                  placeholder="Ne değişmeli? (örn: daha sıcak renkler, insanlar olmasın, daha minimalist...)"
                                  className="w-full rounded-lg border border-purple-200 bg-white px-3 py-2 text-xs"
                                />
                                <Button onClick={handleRegenerateWithFeedback} disabled={aiGenerating || !imageFeedback.trim()} size="sm" className="w-full bg-purple-600 hover:bg-purple-700">
                                  {aiGenerating ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="mr-1 h-3.5 w-3.5" />}
                                  Feedback ile yeniden üret
                                </Button>
                              </div>
                            )}

                            {/* Back to settings */}
                            <button onClick={() => setAiStep("generate")} className="text-[10px] text-purple-600 hover:underline">
                              Ayarlara geri dön
                            </button>
                          </div>
                        ) : null}
                      </>
                    )}
                  </div>
                )}
              </div>

              {/* Schedule & Occasion */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label className="text-xs font-medium">Tarih/Saat (Istanbul)</Label>
                  <Input type="datetime-local" value={editScheduledAt} onChange={e => setEditScheduledAt(e.target.value)} className="mt-1" />
                </div>
                <div>
                  <Label className="text-xs font-medium">Etiket</Label>
                  <Input value={editOccasion} onChange={e => setEditOccasion(e.target.value)} className="mt-1" placeholder="Özel gün, kampanya..." />
                </div>
              </div>

              {/* Save edit */}
              <Button onClick={handleSaveEdit} disabled={editSaving} size="sm" className="w-full">
                {editSaving ? "Kaydediliyor..." : "Değişiklikleri Kaydet"}
              </Button>

              {/* Feedback / Fix — for DRAFT posts */}
              {(selectedPost.status === "DRAFT" || selectedPost.status === "FAILED") && (
                <div className="border-t pt-4">
                  <Label className="text-xs font-medium flex items-center gap-1">
                    <ThumbsDown className="h-3 w-3" /> Feedback & Düzelt
                  </Label>
                  <textarea
                    value={feedbackText}
                    onChange={e => setFeedbackText(e.target.value)}
                    placeholder="Bu içeriği nasıl düzeltmemi istersin? (örn: daha kısa yap, emoji ekle, CTA değiştir)"
                    rows={2}
                    className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
                  />
                  {selectedPost.feedback && (
                    <p className="text-[10px] text-amber-600 mt-1">Son feedback: {selectedPost.feedback}</p>
                  )}
                  <Button onClick={() => handleFix(selectedPost)} disabled={fixing || !feedbackText.trim()} size="sm" variant="outline" className="mt-2">
                    {fixing ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="mr-1 h-3.5 w-3.5" />}
                    Düzelt
                  </Button>
                </div>
              )}

              {/* Performance metrics — for POSTED */}
              {selectedPost.status === "POSTED" && (
                <div className="border-t pt-4">
                  <button onClick={() => setShowMetrics(!showMetrics)} className="flex items-center gap-1 text-xs font-medium text-indigo-600 hover:underline">
                    <BarChart3 className="h-3.5 w-3.5" /> Performans Verileri
                  </button>
                  {(selectedPost.likes != null || showMetrics) && (
                    <div className="mt-2 grid grid-cols-4 gap-2">
                      {[
                        { label: "Gösterim", key: "impressions", icon: Eye },
                        { label: "Beğeni", key: "likes", icon: () => <span>♥</span> },
                        { label: "Yanıt", key: "replies", icon: () => <span>💬</span> },
                        { label: "RT", key: "retweets", icon: () => <span>🔁</span> },
                      ].map(m => (
                        <div key={m.key} className="text-center">
                          <p className="text-[10px] text-gray-400">{m.label}</p>
                          {showMetrics ? (
                            <Input
                              type="number"
                              value={metrics[m.key as keyof typeof metrics]}
                              onChange={e => setMetrics({ ...metrics, [m.key]: e.target.value })}
                              className="mt-1 text-center text-sm h-8"
                            />
                          ) : (
                            <p className="text-sm font-bold text-gray-800">
                              {(selectedPost as any)[m.key] ?? "—"}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                  {showMetrics && (
                    <Button onClick={handleSaveMetrics} size="sm" variant="outline" className="mt-2 w-full">
                      Metrikleri Kaydet
                    </Button>
                  )}
                  {selectedPost.externalPostId && (
                    <a
                      href={`https://x.com/pobyai/status/${selectedPost.externalPostId}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 mt-2 text-xs text-indigo-600 hover:underline"
                    >
                      <Twitter className="h-3 w-3" /> X&apos;te Görüntüle
                    </a>
                  )}
                </div>
              )}

              {/* Error message */}
              {selectedPost.errorMessage && (
                <div className="rounded-lg bg-red-50 p-3 text-xs text-red-700">
                  <p className="font-medium">Hata Detayı:</p>
                  <p className="mt-1 break-all">{selectedPost.errorMessage}</p>
                </div>
              )}

              {/* Action buttons */}
              <div className="flex gap-2 border-t pt-4">
                {selectedPost.status === "DRAFT" && (
                  <>
                    <Button onClick={async () => { await updatePost(selectedPost.id, { status: "APPROVED" }); const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id); if (updated) setSelectedPost(updated); await fetchPosts(); }} size="sm" className="flex-1 bg-blue-600 hover:bg-blue-700">
                      <Check className="mr-1 h-3.5 w-3.5" /> Onayla
                    </Button>
                    <Button onClick={async () => { await updatePost(selectedPost.id, { status: "APPROVED" }); handlePublish(selectedPost.id); }} disabled={publishing === selectedPost.id} size="sm" className="flex-1 bg-emerald-600 hover:bg-emerald-700">
                      <Send className="mr-1 h-3.5 w-3.5" /> Onayla & Paylaş
                    </Button>
                  </>
                )}
                {(selectedPost.status === "APPROVED" || selectedPost.status === "SCHEDULED") && (
                  <Button onClick={() => handlePublish(selectedPost.id)} disabled={publishing === selectedPost.id} size="sm" className="flex-1 bg-emerald-600 hover:bg-emerald-700">
                    {publishing === selectedPost.id ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Send className="mr-1 h-3.5 w-3.5" />}
                    Şimdi Paylaş
                  </Button>
                )}
                <Button onClick={() => handleDelete(selectedPost.id)} variant="outline" size="sm" className="text-red-600 hover:bg-red-50">
                  <Trash2 className="mr-1 h-3.5 w-3.5" /> Sil
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ====== CREATE DIALOG ====== */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setShowCreate(false)}>
          <div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl" onClick={e => e.stopPropagation()}>
            <h2 className="text-lg font-bold mb-4">Yeni İçerik</h2>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs">Platform</Label>
                  <select value={form.platform} onChange={e => setForm({ ...form, platform: e.target.value })} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm">
                    <option value="twitter">X (Twitter)</option>
                  </select>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Tür</Label>
                  <select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm">
                    <option value="tweet">Tweet</option>
                    <option value="thread">Thread</option>
                  </select>
                </div>
              </div>

              {form.type === "thread" ? (
                <div className="space-y-2">
                  <Label className="text-xs">Thread İçerikleri</Label>
                  {form.threadPosts.map((t, i) => (
                    <div key={i} className="flex gap-2">
                      <span className="text-xs text-gray-400 pt-2 shrink-0">{i + 1}/</span>
                      <div className="flex-1">
                        <textarea
                          value={t}
                          onChange={e => {
                            const updated = [...form.threadPosts];
                            updated[i] = e.target.value;
                            setForm({ ...form, threadPosts: updated });
                          }}
                          placeholder={`Tweet ${i + 1}...`}
                          rows={2}
                          className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                          maxLength={280}
                        />
                        <p className="text-right text-[10px] text-gray-400">{t.length}/280</p>
                      </div>
                    </div>
                  ))}
                  <button onClick={() => setForm({ ...form, threadPosts: [...form.threadPosts, ""] })} className="text-xs text-[#4F46E5] hover:underline">
                    + Tweet Ekle
                  </button>
                </div>
              ) : (
                <div className="space-y-1.5">
                  <Label className="text-xs">İçerik</Label>
                  <textarea
                    value={form.content}
                    onChange={e => setForm({ ...form, content: e.target.value })}
                    placeholder="İçerik yazın..."
                    rows={4}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                    maxLength={280}
                  />
                  <p className="text-right text-[10px] text-gray-400">{form.content.length}/280</p>
                </div>
              )}

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs">Tarih/Saat (Istanbul)</Label>
                  <Input type="datetime-local" value={form.scheduledAt} onChange={e => setForm({ ...form, scheduledAt: e.target.value })} />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Etiket (opsiyonel)</Label>
                  <Input value={form.occasion} onChange={e => setForm({ ...form, occasion: e.target.value })} placeholder="Özel gün, kampanya..." />
                </div>
              </div>

              <div className="flex gap-3 pt-2">
                <Button onClick={handleCreate} disabled={saving} className="flex-1">
                  {saving ? "Kaydediliyor..." : "Taslak Olarak Kaydet"}
                </Button>
                <Button variant="outline" onClick={() => setShowCreate(false)}>İptal</Button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Lightbox */}
      {lightboxUrl && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 backdrop-blur-sm" onClick={() => setLightboxUrl(null)}>
          <button onClick={() => setLightboxUrl(null)} className="absolute top-4 right-4 rounded-full bg-white/10 p-2 text-white hover:bg-white/20">
            <X className="h-5 w-5" />
          </button>
          <img src={lightboxUrl} alt="Preview" className="max-h-[85vh] max-w-[90vw] rounded-xl object-contain shadow-2xl" onClick={e => e.stopPropagation()} />
        </div>
      )}
    </div>
  );
}
