"use client";

import { useEffect, useState, useRef } from "react";
import {
  Plus, Send, Trash2, Check, Clock, AlertCircle, Twitter,
  Edit, Calendar, Sparkles, Loader2, X, ImagePlus, Eye,
  ThumbsDown, BarChart3, RefreshCw, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";

interface Post {
  id: string;
  type: string;
  platform: string;
  content: string | null;
  threadContent: string | null;
  imageUrl: string | null;
  scheduledAt: string;
  postedAt: string | null;
  status: string;
  occasion: string | null;
  externalPostId: string | null;
  errorMessage: string | null;
  feedback: string | null;
  impressions: number | null;
  likes: number | null;
  replies: number | null;
  retweets: number | null;
  isAutoGenerated: boolean;
  createdAt: string;
}

const STATUS_CONFIG: Record<string, { label: string; color: string; icon: any }> = {
  DRAFT: { label: "Taslak", color: "bg-gray-100 text-gray-700", icon: Edit },
  APPROVED: { label: "Onaylı", color: "bg-blue-100 text-blue-700", icon: Check },
  SCHEDULED: { label: "Zamanlandı", color: "bg-purple-100 text-purple-700", icon: Clock },
  POSTED: { label: "Paylaşıldı", color: "bg-emerald-100 text-emerald-700", icon: Check },
  FAILED: { label: "Hata", color: "bg-red-100 text-red-700", icon: AlertCircle },
  CANCELLED: { label: "İptal", color: "bg-gray-100 text-gray-500", icon: AlertCircle },
};

const TYPE_LABELS: Record<string, string> = { tweet: "Tweet", thread: "Thread", poll: "Anket" };
const DAYS = ["Pzr", "Pzt", "Sal", "Çar", "Per", "Cum", "Cmt"];

// Format date to Istanbul timezone display
function formatIstanbul(dateStr: string) {
  return new Date(dateStr).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });
}

export default function AdminMarketingPage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState("all");
  const [showCreate, setShowCreate] = useState(false);
  const [publishing, setPublishing] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [selectedPost, setSelectedPost] = useState<Post | null>(null);
  const [fixing, setFixing] = useState(false);
  const [feedbackText, setFeedbackText] = useState("");

  // Create form
  const [form, setForm] = useState({
    type: "tweet",
    platform: "twitter",
    content: "",
    threadPosts: [""],
    scheduledAt: "",
    occasion: "",
  });
  const [saving, setSaving] = useState(false);

  // Edit state in detail modal
  const [editContent, setEditContent] = useState("");
  const [editThreadContent, setEditThreadContent] = useState<string[]>([]);
  const [editScheduledAt, setEditScheduledAt] = useState("");
  const [editOccasion, setEditOccasion] = useState("");
  const [editSaving, setEditSaving] = useState(false);

  // Image upload
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Metrics edit
  const [showMetrics, setShowMetrics] = useState(false);
  const [metrics, setMetrics] = useState({ impressions: "", likes: "", replies: "", retweets: "" });

  useEffect(() => { fetchPosts(); }, []);

  async function fetchPosts() {
    try {
      const res = await fetch("/api/admin/marketing");
      if (res.ok) {
        const data = await res.json();
        setPosts(data.posts || []);
      }
    } catch {} finally { setLoading(false); }
  }

  async function handleCreate() {
    setSaving(true);
    try {
      const body: any = {
        type: form.type,
        platform: form.platform,
        content: form.type === "thread" ? form.threadPosts[0] : form.content,
        scheduledAt: form.scheduledAt || new Date().toISOString(),
        occasion: form.occasion || undefined,
      };
      if (form.type === "thread") {
        body.threadContent = form.threadPosts.filter(t => t.trim());
      }
      const res = await fetch("/api/admin/marketing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (res.ok) {
        await fetchPosts();
        setShowCreate(false);
        setForm({ type: "tweet", platform: "twitter", content: "", threadPosts: [""], scheduledAt: "", occasion: "" });
      }
    } catch {} finally { setSaving(false); }
  }

  async function updatePost(id: string, data: any) {
    await fetch("/api/admin/marketing", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, ...data }),
    });
    await fetchPosts();
  }

  async function handlePublish(id: string) {
    setPublishing(id);
    try {
      const res = await fetch("/api/admin/marketing/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      const data = await res.json();
      if (!res.ok) alert(`Hata: ${data.error || "Bilinmeyen hata"}`);
      await fetchPosts();
      // Refresh selected post
      if (selectedPost?.id === id) {
        const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === id);
        if (updated) setSelectedPost(updated);
      }
    } catch {} finally { setPublishing(null); }
  }

  async function handleDelete(id: string) {
    if (!confirm("Bu içeriği silmek istediğinize emin misiniz?")) return;
    await fetch("/api/admin/marketing", {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id }),
    });
    setSelectedPost(null);
    fetchPosts();
  }

  async function handleFix(post: Post) {
    if (!feedbackText.trim()) return;
    setFixing(true);
    try {
      const res = await fetch("/api/admin/marketing/fix-content", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: post.id, feedback: feedbackText }),
      });
      if (res.ok) {
        setFeedbackText("");
        await fetchPosts();
        const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === post.id);
        if (updated) setSelectedPost(updated);
      } else {
        const data = await res.json();
        alert(`Hata: ${data.error}`);
      }
    } catch {} finally { setFixing(false); }
  }

  async function handleImageUpload(postId: string, file: File) {
    setUploading(true);
    try {
      const formData = new FormData();
      formData.append("file", file);
      const res = await fetch("/api/admin/marketing/upload", { method: "POST", body: formData });
      if (res.ok) {
        const { imageUrl } = await res.json();
        await updatePost(postId, { imageUrl });
        const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === postId);
        if (updated) setSelectedPost(updated);
      }
    } catch {} finally { setUploading(false); }
  }

  async function handleSaveEdit() {
    if (!selectedPost) return;
    setEditSaving(true);
    try {
      const data: any = {
        content: editContent,
        scheduledAt: editScheduledAt,
        occasion: editOccasion,
      };
      if (selectedPost.type === "thread") {
        data.threadContent = editThreadContent.filter(t => t.trim());
        data.content = editThreadContent[0] || editContent;
      }
      await updatePost(selectedPost.id, data);
      const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id);
      if (updated) setSelectedPost(updated);
    } catch {} finally { setEditSaving(false); }
  }

  async function handleSaveMetrics() {
    if (!selectedPost) return;
    await updatePost(selectedPost.id, {
      impressions: metrics.impressions ? Number(metrics.impressions) : null,
      likes: metrics.likes ? Number(metrics.likes) : null,
      replies: metrics.replies ? Number(metrics.replies) : null,
      retweets: metrics.retweets ? Number(metrics.retweets) : null,
    });
    const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id);
    if (updated) setSelectedPost(updated);
    setShowMetrics(false);
  }

  function openDetailModal(post: Post) {
    setSelectedPost(post);
    setEditContent(post.content || "");
    setEditThreadContent(post.threadContent ? JSON.parse(post.threadContent) : []);
    setEditScheduledAt(new Date(post.scheduledAt).toLocaleString("sv-SE", { timeZone: "Europe/Istanbul" }).replace(" ", "T").slice(0, 16));
    setEditOccasion(post.occasion || "");
    setFeedbackText("");
    setShowMetrics(false);
    setMetrics({
      impressions: String(post.impressions || ""),
      likes: String(post.likes || ""),
      replies: String(post.replies || ""),
      retweets: String(post.retweets || ""),
    });
  }

  const filteredPosts = tab === "all" ? posts : posts.filter(p => p.status === tab.toUpperCase());

  // Weekly calendar
  const today = new Date();
  const startOfWeek = new Date(today);
  startOfWeek.setDate(today.getDate() - today.getDay() + 1);
  const weekDays = Array.from({ length: 7 }, (_, i) => {
    const d = new Date(startOfWeek);
    d.setDate(startOfWeek.getDate() + i);
    return d;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-bold text-gray-900">Content Studio</h1>
          <p className="text-xs text-gray-500">İçerik oluştur, zamanla, paylaş</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={async () => {
            setGenerating(true);
            const res = await fetch("/api/admin/marketing/generate-weekly", { method: "POST" });
            const data = await res.json();
            if (res.ok) alert(`${data.created} içerik oluşturuldu! (${data.week})`);
            else alert(`Hata: ${data.error}`);
            await fetchPosts();
            setGenerating(false);
          }} disabled={generating}>
            {generating ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1 h-3.5 w-3.5" />}
            Haftalık Üret
          </Button>
          <Button onClick={() => setShowCreate(true)} size="sm">
            <Plus className="mr-1 h-3.5 w-3.5" /> Oluştur
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
        {[
          { label: "Taslak", count: posts.filter(p => p.status === "DRAFT").length, color: "text-gray-600" },
          { label: "Onaylı", count: posts.filter(p => p.status === "APPROVED").length, color: "text-blue-600" },
          { label: "Zamanlandı", count: posts.filter(p => p.status === "SCHEDULED").length, color: "text-purple-600" },
          { label: "Paylaşıldı", count: posts.filter(p => p.status === "POSTED").length, color: "text-emerald-600" },
          { label: "Hata", count: posts.filter(p => p.status === "FAILED").length, color: "text-red-600" },
        ].map(s => (
          <Card key={s.label}>
            <CardContent className="p-3 text-center">
              <p className="text-[10px] text-gray-400 uppercase">{s.label}</p>
              <p className={`text-lg font-bold ${s.color}`}>{s.count}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Weekly Calendar */}
      <Card>
        <CardHeader className="py-3 px-4">
          <CardTitle className="text-sm">Haftalık Takvim</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="grid grid-cols-7 border-t">
            {weekDays.map((day, i) => {
              const dayStr = day.toISOString().split("T")[0];
              const dayPosts = posts.filter(p => {
                const pDate = new Date(p.scheduledAt).toLocaleDateString("sv-SE", { timeZone: "Europe/Istanbul" });
                return pDate === dayStr;
              });
              const isToday = dayStr === today.toISOString().split("T")[0];
              return (
                <div key={i} className={`border-r last:border-0 p-2 min-h-[80px] ${isToday ? "bg-[#EEF2FF]/30" : ""}`}>
                  <p className={`text-[10px] font-semibold ${isToday ? "text-[#4F46E5]" : "text-gray-400"}`}>
                    {DAYS[day.getDay()]} {day.getDate()}
                  </p>
                  <div className="mt-1 space-y-1">
                    {dayPosts.map(p => {
                      const cfg = STATUS_CONFIG[p.status] || STATUS_CONFIG.DRAFT;
                      return (
                        <div
                          key={p.id}
                          onClick={() => openDetailModal(p)}
                          className={`rounded px-1.5 py-0.5 text-[9px] font-medium truncate cursor-pointer hover:ring-1 hover:ring-indigo-300 ${cfg.color}`}
                        >
                          {p.content?.slice(0, 25) || "Thread"}
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Content List */}
      <Tabs value={tab} onValueChange={setTab}>
        <div className="overflow-x-auto">
          <TabsList className="w-max sm:w-auto">
            <TabsTrigger value="all" className="text-xs">Tümü ({posts.length})</TabsTrigger>
            <TabsTrigger value="draft" className="text-xs">Taslak</TabsTrigger>
            <TabsTrigger value="approved" className="text-xs">Onaylı</TabsTrigger>
            <TabsTrigger value="posted" className="text-xs">Paylaşıldı</TabsTrigger>
            <TabsTrigger value="failed" className="text-xs">Hata</TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value={tab}>
          {loading ? (
            <p className="text-sm text-gray-400 py-8 text-center">Yükleniyor...</p>
          ) : filteredPosts.length === 0 ? (
            <div className="py-12 text-center">
              <Calendar className="mx-auto mb-3 h-8 w-8 text-gray-300" />
              <p className="text-sm text-gray-500">Henüz içerik yok</p>
              <Button size="sm" variant="outline" className="mt-3" onClick={() => setShowCreate(true)}>
                <Plus className="mr-1 h-3 w-3" /> İlk İçeriği Oluştur
              </Button>
            </div>
          ) : (
            <div className="space-y-2">
              {filteredPosts.map(post => {
                const cfg = STATUS_CONFIG[post.status] || STATUS_CONFIG.DRAFT;
                const StatusIcon = cfg.icon;
                return (
                  <Card key={post.id} className="cursor-pointer hover:ring-1 hover:ring-indigo-200 transition-all" onClick={() => openDetailModal(post)}>
                    <CardContent className="p-3">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                            <Twitter className="h-3.5 w-3.5 text-gray-400" />
                            <span className="text-[10px] font-medium text-gray-500 uppercase">{TYPE_LABELS[post.type] || post.type}</span>
                            <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${cfg.color}`}>
                              <StatusIcon className="h-2.5 w-2.5" /> {cfg.label}
                            </span>
                            {post.imageUrl && <ImagePlus className="h-3 w-3 text-indigo-400" />}
                            {post.isAutoGenerated && <Zap className="h-3 w-3 text-amber-400" />}
                          </div>
                          <p className="text-sm text-gray-800 whitespace-pre-wrap line-clamp-2">
                            {post.content || (post.threadContent ? `Thread (${JSON.parse(post.threadContent).length} tweet)` : "—")}
                          </p>
                          <div className="flex items-center gap-3 mt-1.5 text-[10px] text-gray-400">
                            <span>{formatIstanbul(post.scheduledAt)}</span>
                            {post.occasion && <span>· {post.occasion}</span>}
                            {post.likes != null && (
                              <span className="text-indigo-500">· {post.likes} like · {post.retweets} RT</span>
                            )}
                          </div>
                        </div>
                        <div className="flex items-center gap-1 shrink-0" onClick={e => e.stopPropagation()}>
                          {post.status === "DRAFT" && (
                            <>
                              <button onClick={() => updatePost(post.id, { status: "APPROVED" })} className="rounded-lg bg-blue-50 p-1.5 text-blue-600 hover:bg-blue-100" title="Onayla">
                                <Check className="h-3.5 w-3.5" />
                              </button>
                              <button onClick={async () => { await updatePost(post.id, { status: "APPROVED" }); handlePublish(post.id); }} disabled={publishing === post.id} className="rounded-lg bg-emerald-50 p-1.5 text-emerald-600 hover:bg-emerald-100 disabled:opacity-50" title="Onayla & Paylaş">
                                <Send className="h-3.5 w-3.5" />
                              </button>
                            </>
                          )}
                          {(post.status === "APPROVED" || post.status === "SCHEDULED") && (
                            <button onClick={() => handlePublish(post.id)} disabled={publishing === post.id} className="rounded-lg bg-emerald-50 p-1.5 text-emerald-600 hover:bg-emerald-100 disabled:opacity-50" title="Şimdi Paylaş">
                              <Send className="h-3.5 w-3.5" />
                            </button>
                          )}
                          <button onClick={() => handleDelete(post.id)} className="rounded-lg p-1.5 text-gray-400 hover:bg-red-50 hover:text-red-500" title="Sil">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* ====== DETAIL MODAL ====== */}
      {selectedPost && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setSelectedPost(null)}>
          <div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Twitter className="h-4 w-4 text-gray-400" />
                <span className="text-xs font-medium text-gray-500 uppercase">{TYPE_LABELS[selectedPost.type] || selectedPost.type}</span>
                {(() => {
                  const cfg = STATUS_CONFIG[selectedPost.status] || STATUS_CONFIG.DRAFT;
                  const Icon = cfg.icon;
                  return (
                    <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${cfg.color}`}>
                      <Icon className="h-2.5 w-2.5" /> {cfg.label}
                    </span>
                  );
                })()}
              </div>
              <button onClick={() => setSelectedPost(null)} className="rounded-lg p-1.5 hover:bg-gray-100">
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Content Edit */}
            <div className="space-y-4">
              {selectedPost.type === "thread" ? (
                <div className="space-y-2">
                  <Label className="text-xs font-medium">Thread İçerikleri</Label>
                  {editThreadContent.map((t, i) => (
                    <div key={i} className="flex gap-2">
                      <span className="text-xs text-gray-400 pt-2 shrink-0">{i + 1}/</span>
                      <div className="flex-1">
                        <textarea
                          value={t}
                          onChange={e => {
                            const updated = [...editThreadContent];
                            updated[i] = e.target.value;
                            setEditThreadContent(updated);
                          }}
                          rows={2}
                          className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400"
                          maxLength={280}
                        />
                        <p className="text-right text-[10px] text-gray-400">{t.length}/280</p>
                      </div>
                    </div>
                  ))}
                  <button onClick={() => setEditThreadContent([...editThreadContent, ""])} className="text-xs text-indigo-600 hover:underline">+ Tweet Ekle</button>
                </div>
              ) : (
                <div>
                  <Label className="text-xs font-medium">İçerik</Label>
                  <textarea
                    value={editContent}
                    onChange={e => setEditContent(e.target.value)}
                    rows={4}
                    className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400"
                    maxLength={280}
                  />
                  <p className="text-right text-[10px] text-gray-400">{editContent.length}/280</p>
                </div>
              )}

              {/* Image */}
              <div>
                <Label className="text-xs font-medium">Görsel</Label>
                <div className="mt-1 flex items-center gap-3">
                  {selectedPost.imageUrl ? (
                    <div className="relative">
                      <img src={selectedPost.imageUrl} alt="" className="h-20 w-20 rounded-lg object-cover border" />
                      <button
                        onClick={async () => { await updatePost(selectedPost.id, { imageUrl: null }); const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id); if (updated) setSelectedPost(updated); }}
                        className="absolute -top-1 -right-1 rounded-full bg-red-500 p-0.5 text-white"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </div>
                  ) : null}
                  <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={e => {
                    const file = e.target.files?.[0];
                    if (file && selectedPost) handleImageUpload(selectedPost.id, file);
                  }} />
                  <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()} disabled={uploading}>
                    {uploading ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <ImagePlus className="mr-1 h-3.5 w-3.5" />}
                    {selectedPost.imageUrl ? "Değiştir" : "Görsel Ekle"}
                  </Button>
                </div>
              </div>

              {/* Schedule & Occasion */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label className="text-xs font-medium">Tarih/Saat (Istanbul)</Label>
                  <Input type="datetime-local" value={editScheduledAt} onChange={e => setEditScheduledAt(e.target.value)} className="mt-1" />
                </div>
                <div>
                  <Label className="text-xs font-medium">Etiket</Label>
                  <Input value={editOccasion} onChange={e => setEditOccasion(e.target.value)} className="mt-1" placeholder="Özel gün, kampanya..." />
                </div>
              </div>

              {/* Save edit */}
              <Button onClick={handleSaveEdit} disabled={editSaving} size="sm" className="w-full">
                {editSaving ? "Kaydediliyor..." : "Değişiklikleri Kaydet"}
              </Button>

              {/* Feedback / Fix — for DRAFT posts */}
              {(selectedPost.status === "DRAFT" || selectedPost.status === "FAILED") && (
                <div className="border-t pt-4">
                  <Label className="text-xs font-medium flex items-center gap-1">
                    <ThumbsDown className="h-3 w-3" /> Feedback & Düzelt
                  </Label>
                  <textarea
                    value={feedbackText}
                    onChange={e => setFeedbackText(e.target.value)}
                    placeholder="Bu içeriği nasıl düzeltmemi istersin? (örn: daha kısa yap, emoji ekle, CTA değiştir)"
                    rows={2}
                    className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
                  />
                  {selectedPost.feedback && (
                    <p className="text-[10px] text-amber-600 mt-1">Son feedback: {selectedPost.feedback}</p>
                  )}
                  <Button onClick={() => handleFix(selectedPost)} disabled={fixing || !feedbackText.trim()} size="sm" variant="outline" className="mt-2">
                    {fixing ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="mr-1 h-3.5 w-3.5" />}
                    Düzelt
                  </Button>
                </div>
              )}

              {/* Performance metrics — for POSTED */}
              {selectedPost.status === "POSTED" && (
                <div className="border-t pt-4">
                  <button onClick={() => setShowMetrics(!showMetrics)} className="flex items-center gap-1 text-xs font-medium text-indigo-600 hover:underline">
                    <BarChart3 className="h-3.5 w-3.5" /> Performans Verileri
                  </button>
                  {(selectedPost.likes != null || showMetrics) && (
                    <div className="mt-2 grid grid-cols-4 gap-2">
                      {[
                        { label: "Gösterim", key: "impressions", icon: Eye },
                        { label: "Beğeni", key: "likes", icon: () => <span>♥</span> },
                        { label: "Yanıt", key: "replies", icon: () => <span>💬</span> },
                        { label: "RT", key: "retweets", icon: () => <span>🔁</span> },
                      ].map(m => (
                        <div key={m.key} className="text-center">
                          <p className="text-[10px] text-gray-400">{m.label}</p>
                          {showMetrics ? (
                            <Input
                              type="number"
                              value={metrics[m.key as keyof typeof metrics]}
                              onChange={e => setMetrics({ ...metrics, [m.key]: e.target.value })}
                              className="mt-1 text-center text-sm h-8"
                            />
                          ) : (
                            <p className="text-sm font-bold text-gray-800">
                              {(selectedPost as any)[m.key] ?? "—"}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                  {showMetrics && (
                    <Button onClick={handleSaveMetrics} size="sm" variant="outline" className="mt-2 w-full">
                      Metrikleri Kaydet
                    </Button>
                  )}
                  {selectedPost.externalPostId && (
                    <a
                      href={`https://x.com/pobyai/status/${selectedPost.externalPostId}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 mt-2 text-xs text-indigo-600 hover:underline"
                    >
                      <Twitter className="h-3 w-3" /> X&apos;te Görüntüle
                    </a>
                  )}
                </div>
              )}

              {/* Error message */}
              {selectedPost.errorMessage && (
                <div className="rounded-lg bg-red-50 p-3 text-xs text-red-700">
                  <p className="font-medium">Hata Detayı:</p>
                  <p className="mt-1 break-all">{selectedPost.errorMessage}</p>
                </div>
              )}

              {/* Action buttons */}
              <div className="flex gap-2 border-t pt-4">
                {selectedPost.status === "DRAFT" && (
                  <>
                    <Button onClick={async () => { await updatePost(selectedPost.id, { status: "APPROVED" }); const updated = (await (await fetch("/api/admin/marketing")).json()).posts?.find((p: Post) => p.id === selectedPost.id); if (updated) setSelectedPost(updated); await fetchPosts(); }} size="sm" className="flex-1 bg-blue-600 hover:bg-blue-700">
                      <Check className="mr-1 h-3.5 w-3.5" /> Onayla
                    </Button>
                    <Button onClick={async () => { await updatePost(selectedPost.id, { status: "APPROVED" }); handlePublish(selectedPost.id); }} disabled={publishing === selectedPost.id} size="sm" className="flex-1 bg-emerald-600 hover:bg-emerald-700">
                      <Send className="mr-1 h-3.5 w-3.5" /> Onayla & Paylaş
                    </Button>
                  </>
                )}
                {(selectedPost.status === "APPROVED" || selectedPost.status === "SCHEDULED") && (
                  <Button onClick={() => handlePublish(selectedPost.id)} disabled={publishing === selectedPost.id} size="sm" className="flex-1 bg-emerald-600 hover:bg-emerald-700">
                    {publishing === selectedPost.id ? <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" /> : <Send className="mr-1 h-3.5 w-3.5" />}
                    Şimdi Paylaş
                  </Button>
                )}
                <Button onClick={() => handleDelete(selectedPost.id)} variant="outline" size="sm" className="text-red-600 hover:bg-red-50">
                  <Trash2 className="mr-1 h-3.5 w-3.5" /> Sil
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ====== CREATE DIALOG ====== */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setShowCreate(false)}>
          <div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl" onClick={e => e.stopPropagation()}>
            <h2 className="text-lg font-bold mb-4">Yeni İçerik</h2>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs">Platform</Label>
                  <select value={form.platform} onChange={e => setForm({ ...form, platform: e.target.value })} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm">
                    <option value="twitter">X (Twitter)</option>
                  </select>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Tür</Label>
                  <select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm">
                    <option value="tweet">Tweet</option>
                    <option value="thread">Thread</option>
                  </select>
                </div>
              </div>

              {form.type === "thread" ? (
                <div className="space-y-2">
                  <Label className="text-xs">Thread İçerikleri</Label>
                  {form.threadPosts.map((t, i) => (
                    <div key={i} className="flex gap-2">
                      <span className="text-xs text-gray-400 pt-2 shrink-0">{i + 1}/</span>
                      <div className="flex-1">
                        <textarea
                          value={t}
                          onChange={e => {
                            const updated = [...form.threadPosts];
                            updated[i] = e.target.value;
                            setForm({ ...form, threadPosts: updated });
                          }}
                          placeholder={`Tweet ${i + 1}...`}
                          rows={2}
                          className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                          maxLength={280}
                        />
                        <p className="text-right text-[10px] text-gray-400">{t.length}/280</p>
                      </div>
                    </div>
                  ))}
                  <button onClick={() => setForm({ ...form, threadPosts: [...form.threadPosts, ""] })} className="text-xs text-[#4F46E5] hover:underline">
                    + Tweet Ekle
                  </button>
                </div>
              ) : (
                <div className="space-y-1.5">
                  <Label className="text-xs">İçerik</Label>
                  <textarea
                    value={form.content}
                    onChange={e => setForm({ ...form, content: e.target.value })}
                    placeholder="İçerik yazın..."
                    rows={4}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                    maxLength={280}
                  />
                  <p className="text-right text-[10px] text-gray-400">{form.content.length}/280</p>
                </div>
              )}

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs">Tarih/Saat (Istanbul)</Label>
                  <Input type="datetime-local" value={form.scheduledAt} onChange={e => setForm({ ...form, scheduledAt: e.target.value })} />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Etiket (opsiyonel)</Label>
                  <Input value={form.occasion} onChange={e => setForm({ ...form, occasion: e.target.value })} placeholder="Özel gün, kampanya..." />
                </div>
              </div>

              <div className="flex gap-3 pt-2">
                <Button onClick={handleCreate} disabled={saving} className="flex-1">
                  {saving ? "Kaydediliyor..." : "Taslak Olarak Kaydet"}
                </Button>
                <Button variant="outline" onClick={() => setShowCreate(false)}>İptal</Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
