"use client";

import { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import {
  Share2,
  Upload,
  Plus,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Loader2,
  Image as ImageIcon,
  Clock,
  CheckCircle,
  XCircle,
  X,
  Sparkles,
  Instagram,
  Facebook,
} from "lucide-react";

interface SocialMediaAsset {
  id: string;
  fileName: string;
  fileUrl: string;
  type: string;
  createdAt: string;
}

interface ScheduledPost {
  id: string;
  type: string;
  platform: string;
  content: string | null;
  imageUrl: string | null;
  scheduledAt: string;
  status: string;
  isAutoGenerated: boolean;
  occasion: string | null;
}

const TURKISH_HOLIDAYS = [
  { date: "01-01", name: "Yılbaşı" },
  { date: "04-23", name: "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı" },
  { date: "05-01", name: "Emek ve Dayanışma Günü" },
  { date: "05-11", name: "Anneler Günü" },
  { date: "05-19", name: "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı" },
  { date: "06-15", name: "Babalar Günü" },
  { date: "07-15", name: "15 Temmuz Demokrasi ve Milli Birlik Günü" },
  { date: "08-30", name: "30 Ağustos Zafer Bayramı" },
  { date: "10-29", name: "29 Ekim Cumhuriyet Bayramı" },
  { date: "11-10", name: "10 Kasım Atatürk'ü Anma Günü" },
  { date: "11-24", name: "Öğretmenler Günü" },
  { date: "02-14", name: "Sevgililer Günü" },
  { date: "03-08", name: "Dünya Kadınlar Günü" },
  { date: "03-21", name: "Nevruz" },
];

const statusConfig: Record<string, { label: string; color: string; icon: typeof Clock }> = {
  SCHEDULED: { label: "Planlandı", color: "bg-blue-100 text-blue-700", icon: Clock },
  POSTED: { label: "Paylaşıldı", color: "bg-green-100 text-green-700", icon: CheckCircle },
  FAILED: { label: "Başarısız", color: "bg-red-100 text-red-700", icon: XCircle },
  CANCELLED: { label: "İptal", color: "bg-gray-100 text-gray-700", icon: XCircle },
};

const MONTHS_TR = [
  "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran",
  "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık",
];
const DAYS_TR = ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"];

function Skeleton({ className }: { className?: string }) {
  return <div className={`animate-pulse rounded-xl bg-gray-100 ${className || ""}`} />;
}

export default function SocialMediaPage() {
  const [assets, setAssets] = useState<SocialMediaAsset[]>([]);
  const [posts, setPosts] = useState<ScheduledPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [showNewPost, setShowNewPost] = useState(false);
  const [autoHoliday, setAutoHoliday] = useState(false);
  const [generatingContent, setGeneratingContent] = useState(false);

  // Calendar state
  const [calYear, setCalYear] = useState(new Date().getFullYear());
  const [calMonth, setCalMonth] = useState(new Date().getMonth());

  // New post form
  const [newPost, setNewPost] = useState({
    platform: "instagram",
    content: "",
    scheduledAt: "",
    imageUrl: "",
    occasion: "",
  });

  const fetchData = useCallback(async () => {
    try {
      const [assetsRes, postsRes] = await Promise.all([
        fetch("/api/social-media/assets"),
        fetch("/api/social-media/schedule"),
      ]);
      if (assetsRes.ok) setAssets(await assetsRes.json());
      if (postsRes.ok) setPosts(await postsRes.json());
    } catch {
      // Handle error
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  async function handleUploadAsset(files: FileList | null) {
    if (!files || files.length === 0) return;
    setUploading(true);
    for (const file of Array.from(files)) {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("type", file.type.startsWith("video") ? "video" : "image");
      try {
        await fetch("/api/social-media/assets", { method: "POST", body: formData });
      } catch {
        // Handle error
      }
    }
    await fetchData();
    setUploading(false);
  }

  async function handleCreatePost(e: React.FormEvent) {
    e.preventDefault();
    try {
      const res = await fetch("/api/social-media/schedule", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "post",
          platform: newPost.platform,
          content: newPost.content,
          imageUrl: newPost.imageUrl || null,
          scheduledAt: newPost.scheduledAt,
          occasion: newPost.occasion || null,
        }),
      });
      if (res.ok) {
        setShowNewPost(false);
        setNewPost({ platform: "instagram", content: "", scheduledAt: "", imageUrl: "", occasion: "" });
        await fetchData();
      }
    } catch {
      // Handle error
    }
  }

  async function handleGenerateContent(occasion: string) {
    setGeneratingContent(true);
    try {
      const res = await fetch("/api/social-media/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ occasion, platform: newPost.platform }),
      });
      if (res.ok) {
        const data = await res.json();
        setNewPost((prev) => ({ ...prev, content: data.content, occasion }));
      }
    } catch {
      // Handle error
    } finally {
      setGeneratingContent(false);
    }
  }

  async function handleAutoHolidayToggle() {
    const newState = !autoHoliday;
    setAutoHoliday(newState);

    if (newState) {
      // Create auto posts for upcoming holidays
      const now = new Date();
      for (const holiday of TURKISH_HOLIDAYS) {
        const [mm, dd] = holiday.date.split("-");
        const holidayDate = new Date(now.getFullYear(), parseInt(mm) - 1, parseInt(dd), 10, 0);
        if (holidayDate < now) {
          holidayDate.setFullYear(now.getFullYear() + 1);
        }

        try {
          await fetch("/api/social-media/schedule", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              type: "post",
              platform: "instagram",
              content: `${holiday.name} kutlu olsun!`,
              scheduledAt: holidayDate.toISOString(),
              isAutoGenerated: true,
              occasion: holiday.name,
            }),
          });
        } catch {
          // Handle error
        }
      }
      await fetchData();
    }
  }

  // Calendar helpers
  function getDaysInMonth(year: number, month: number) {
    return new Date(year, month + 1, 0).getDate();
  }

  function getFirstDayOfMonth(year: number, month: number) {
    const day = new Date(year, month, 1).getDay();
    return day === 0 ? 6 : day - 1; // Monday = 0
  }

  function getPostsForDate(year: number, month: number, day: number) {
    return posts.filter((p) => {
      const d = new Date(p.scheduledAt);
      return d.getFullYear() === year && d.getMonth() === month && d.getDate() === day;
    });
  }

  function getHolidayForDate(month: number, day: number) {
    const key = `${(month + 1).toString().padStart(2, "0")}-${day.toString().padStart(2, "0")}`;
    return TURKISH_HOLIDAYS.find((h) => h.date === key);
  }

  const daysInMonth = getDaysInMonth(calYear, calMonth);
  const firstDay = getFirstDayOfMonth(calYear, calMonth);

  function prevMonth() {
    if (calMonth === 0) { setCalMonth(11); setCalYear(calYear - 1); }
    else setCalMonth(calMonth - 1);
  }
  function nextMonth() {
    if (calMonth === 11) { setCalMonth(0); setCalYear(calYear + 1); }
    else setCalMonth(calMonth + 1);
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"
      >
        <div className="flex items-center gap-2">
          <Share2 className="h-5 w-5 text-blue-600" />
          <h2 className="text-lg font-semibold text-gray-900">Sosyal Medya</h2>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleAutoHolidayToggle}
            className={`inline-flex items-center gap-1.5 rounded-xl px-4 py-2 text-xs font-semibold transition-colors ${
              autoHoliday
                ? "bg-amber-100 text-amber-700"
                : "border border-gray-200 text-gray-600 hover:bg-gray-50"
            }`}
          >
            <Sparkles className="h-3.5 w-3.5" />
            {autoHoliday ? "Otomatik Kutlama Aktif" : "Otomatik Kutlama"}
          </button>
          <button
            onClick={() => setShowNewPost(true)}
            className="inline-flex items-center gap-1.5 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-blue-700"
          >
            <Plus className="h-3.5 w-3.5" />
            Yeni Paylaşım
          </button>
        </div>
      </motion.div>

      {loading ? (
        <div className="space-y-4">
          <Skeleton className="h-64" />
          <Skeleton className="h-48" />
        </div>
      ) : (
        <>
          {/* Assets Upload */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.05 }}
            className="overflow-hidden rounded-2xl border border-gray-100 bg-white"
          >
            <div className="flex items-center justify-between border-b border-gray-100 px-6 py-4">
              <div className="flex items-center gap-2">
                <ImageIcon className="h-4 w-4 text-blue-600" />
                <h3 className="text-sm font-semibold text-gray-900">Görseller</h3>
                {assets.length > 0 && (
                  <span className="rounded-full bg-blue-50 px-2 py-0.5 text-[11px] font-semibold text-blue-700">
                    {assets.length}
                  </span>
                )}
              </div>
              <label className="cursor-pointer inline-flex items-center gap-1.5 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-blue-700">
                {uploading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Upload className="h-3.5 w-3.5" />}
                {uploading ? "Yükleniyor..." : "Görsel Yükle"}
                <input
                  type="file"
                  accept="image/*,video/*"
                  multiple
                  onChange={(e) => handleUploadAsset(e.target.files)}
                  className="hidden"
                  disabled={uploading}
                />
              </label>
            </div>
            <div className="p-4">
              {assets.length === 0 ? (
                <div className="flex min-h-[100px] items-center justify-center">
                  <p className="text-xs text-gray-500">Henüz görsel yüklenmemiş</p>
                </div>
              ) : (
                <div className="flex gap-3 overflow-x-auto pb-2">
                  {assets.map((asset) => (
                    <div key={asset.id} className="shrink-0 overflow-hidden rounded-xl border border-gray-100">
                      <img src={asset.fileUrl} alt={asset.fileName} className="h-20 w-20 object-cover" />
                    </div>
                  ))}
                </div>
              )}
            </div>
          </motion.div>

          {/* Calendar */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.1 }}
            className="overflow-hidden rounded-2xl border border-gray-100 bg-white"
          >
            <div className="flex items-center justify-between border-b border-gray-100 px-6 py-4">
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-blue-600" />
                <h3 className="text-sm font-semibold text-gray-900">İçerik Takvimi</h3>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={prevMonth} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100">
                  <ChevronLeft className="h-4 w-4" />
                </button>
                <span className="text-sm font-medium text-gray-800 min-w-[120px] text-center">
                  {MONTHS_TR[calMonth]} {calYear}
                </span>
                <button onClick={nextMonth} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100">
                  <ChevronRight className="h-4 w-4" />
                </button>
              </div>
            </div>
            <div className="p-4">
              {/* Day headers */}
              <div className="grid grid-cols-7 gap-1 mb-1">
                {DAYS_TR.map((d) => (
                  <div key={d} className="py-2 text-center text-[11px] font-medium text-gray-400">
                    {d}
                  </div>
                ))}
              </div>
              {/* Days */}
              <div className="grid grid-cols-7 gap-1">
                {Array.from({ length: firstDay }).map((_, i) => (
                  <div key={`empty-${i}`} className="h-20" />
                ))}
                {Array.from({ length: daysInMonth }).map((_, i) => {
                  const day = i + 1;
                  const dayPosts = getPostsForDate(calYear, calMonth, day);
                  const holiday = getHolidayForDate(calMonth, day);
                  const isToday =
                    new Date().getFullYear() === calYear &&
                    new Date().getMonth() === calMonth &&
                    new Date().getDate() === day;

                  return (
                    <div
                      key={day}
                      className={`h-20 rounded-lg border p-1.5 text-xs transition-colors ${
                        isToday
                          ? "border-blue-300 bg-blue-50/50"
                          : "border-gray-100 hover:bg-gray-50"
                      }`}
                    >
                      <p className={`text-[11px] font-medium ${isToday ? "text-blue-600" : "text-gray-700"}`}>
                        {day}
                      </p>
                      {holiday && (
                        <p className="mt-0.5 truncate text-[9px] text-amber-600" title={holiday.name}>
                          {holiday.name.length > 12 ? holiday.name.slice(0, 12) + "..." : holiday.name}
                        </p>
                      )}
                      {dayPosts.slice(0, 2).map((p) => (
                        <div
                          key={p.id}
                          className={`mt-0.5 truncate rounded px-1 py-0.5 text-[9px] font-medium ${
                            p.platform === "instagram"
                              ? "bg-pink-100 text-pink-700"
                              : "bg-blue-100 text-blue-700"
                          }`}
                          title={p.content || p.occasion || ""}
                        >
                          {p.platform === "instagram" ? "IG" : "FB"} {p.occasion || (p.content?.slice(0, 10) + "...")}
                        </div>
                      ))}
                      {dayPosts.length > 2 && (
                        <p className="text-[9px] text-gray-400">+{dayPosts.length - 2}</p>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </motion.div>

          {/* Scheduled Posts List */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.15 }}
            className="overflow-hidden rounded-2xl border border-gray-100 bg-white"
          >
            <div className="border-b border-gray-100 px-6 py-4">
              <h3 className="text-sm font-semibold text-gray-900">Planlanan Paylaşımlar</h3>
            </div>
            {posts.length === 0 ? (
              <div className="flex min-h-[120px] items-center justify-center p-6">
                <div className="text-center">
                  <Calendar className="mx-auto mb-2 h-8 w-8 text-gray-300" />
                  <p className="text-xs text-gray-500">Henüz planlanmış paylaşım yok</p>
                </div>
              </div>
            ) : (
              <div className="divide-y divide-gray-50">
                {posts.map((post, i) => {
                  const status = statusConfig[post.status] || statusConfig.SCHEDULED;
                  const StatusIcon = status.icon;
                  return (
                    <motion.div
                      key={post.id}
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3, delay: i * 0.03 }}
                      className="flex items-center justify-between px-6 py-4"
                    >
                      <div className="flex items-center gap-3">
                        <div className={`flex h-9 w-9 items-center justify-center rounded-xl ${
                          post.platform === "instagram" ? "bg-pink-50" : "bg-blue-50"
                        }`}>
                          {post.platform === "instagram" ? (
                            <Instagram className="h-4 w-4 text-pink-600" />
                          ) : (
                            <Facebook className="h-4 w-4 text-blue-600" />
                          )}
                        </div>
                        <div>
                          <p className="text-sm font-medium text-gray-900">
                            {post.occasion || (post.content?.slice(0, 40) + (post.content && post.content.length > 40 ? "..." : ""))}
                          </p>
                          <p className="text-xs text-gray-400">
                            {new Date(post.scheduledAt).toLocaleDateString("tr-TR", {
                              day: "numeric",
                              month: "long",
                              year: "numeric",
                              hour: "2-digit",
                              minute: "2-digit",
                            })}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        {post.isAutoGenerated && (
                          <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-600">
                            Otomatik
                          </span>
                        )}
                        <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold ${status.color}`}>
                          <StatusIcon className="h-3 w-3" />
                          {status.label}
                        </span>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            )}
          </motion.div>
        </>
      )}

      {/* New Post Modal */}
      {showNewPost && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm"
          onClick={() => setShowNewPost(false)}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mx-4 max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">Yeni Paylaşım</h3>
              <button onClick={() => setShowNewPost(false)} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100">
                <X className="h-4 w-4" />
              </button>
            </div>
            <form onSubmit={handleCreatePost} className="space-y-4">
              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-600">Platform</label>
                <div className="flex gap-2">
                  {["instagram", "facebook"].map((p) => (
                    <button
                      key={p}
                      type="button"
                      onClick={() => setNewPost({ ...newPost, platform: p })}
                      className={`flex-1 rounded-xl px-4 py-2.5 text-xs font-semibold transition-colors ${
                        newPost.platform === p
                          ? p === "instagram" ? "bg-pink-600 text-white" : "bg-blue-600 text-white"
                          : "border border-gray-200 text-gray-600 hover:bg-gray-50"
                      }`}
                    >
                      {p === "instagram" ? "Instagram" : "Facebook"}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-600">Tarih ve Saat</label>
                <input
                  type="datetime-local"
                  value={newPost.scheduledAt}
                  onChange={(e) => setNewPost({ ...newPost, scheduledAt: e.target.value })}
                  required
                  className="block w-full rounded-xl border border-gray-200 px-4 py-2.5 text-sm focus:border-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-400/20"
                />
              </div>

              {/* Quick holiday content */}
              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-600">Özel Gün (Opsiyonel)</label>
                <div className="flex flex-wrap gap-1.5 mb-2">
                  {TURKISH_HOLIDAYS.slice(0, 6).map((h) => (
                    <button
                      key={h.date}
                      type="button"
                      onClick={() => handleGenerateContent(h.name)}
                      disabled={generatingContent}
                      className="rounded-lg bg-amber-50 px-2.5 py-1 text-[10px] font-medium text-amber-700 transition-colors hover:bg-amber-100"
                    >
                      {h.name.length > 20 ? h.name.slice(0, 20) + "..." : h.name}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-600">İçerik</label>
                <div className="relative">
                  <textarea
                    value={newPost.content}
                    onChange={(e) => setNewPost({ ...newPost, content: e.target.value })}
                    rows={4}
                    placeholder="Paylaşım içeriği..."
                    className="block w-full rounded-xl border border-gray-200 px-4 py-2.5 text-sm focus:border-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-400/20"
                  />
                  {generatingContent && (
                    <div className="absolute inset-0 flex items-center justify-center rounded-xl bg-white/80">
                      <Loader2 className="h-5 w-5 animate-spin text-blue-600" />
                    </div>
                  )}
                </div>
              </div>

              {/* Select from assets */}
              {assets.length > 0 && (
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-gray-600">Görsel Seç</label>
                  <div className="flex gap-2 overflow-x-auto pb-2">
                    {assets.map((asset) => (
                      <button
                        key={asset.id}
                        type="button"
                        onClick={() => setNewPost({ ...newPost, imageUrl: asset.fileUrl })}
                        className={`shrink-0 overflow-hidden rounded-lg border-2 transition-colors ${
                          newPost.imageUrl === asset.fileUrl
                            ? "border-blue-600"
                            : "border-gray-100 hover:border-gray-300"
                        }`}
                      >
                        <img src={asset.fileUrl} alt={asset.fileName} className="h-16 w-16 object-cover" />
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <button
                type="submit"
                className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
              >
                <Calendar className="h-4 w-4" />
                Planla
              </button>
            </form>
          </motion.div>
        </div>
      )}
    </div>
  );
}
