import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { recordScenario } from "@/lib/video/recorder";
import { getScenario, getAllScenarios } from "@/lib/video/scenarios";

const DEMO_EMAIL = process.env.DEMO_USER_EMAIL || "demo@poby.ai";
const DEMO_PASSWORD = process.env.DEMO_USER_PASSWORD || "Demo2026!";

// GET — list available scenarios
export async function GET() {
  try {
    const session = await auth();
    if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const role = (session.user as any).role;
    if (role !== "ADMIN" && role !== "SUPERADMIN") {
      return NextResponse.json({ error: "Yetkisiz" }, { status: 403 });
    }

    const scenarios = getAllScenarios().map(s => ({
      id: s.id,
      name: s.name,
      description: s.description,
      hookText: s.hookText,
      stepCount: s.steps.length,
    }));

    return NextResponse.json({ scenarios });
  } catch {
    return NextResponse.json({ error: "Bir hata oluştu" }, { status: 500 });
  }
}

// POST — generate video for a scenario
export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const role = (session.user as any).role;
    if (role !== "ADMIN" && role !== "SUPERADMIN") {
      return NextResponse.json({ error: "Yetkisiz" }, { status: 403 });
    }
    const clinicId = (session.user as any).clinicId;

    const { scenarioId, customHook, customCta } = await req.json();
    if (!scenarioId) return NextResponse.json({ error: "Senaryo ID gerekli" }, { status: 400 });

    const scenario = getScenario(scenarioId);
    if (!scenario) return NextResponse.json({ error: "Geçersiz senaryo" }, { status: 400 });

    // Allow custom hook/cta text
    if (customHook) scenario.hookText = customHook;
    if (customCta) scenario.ctaText = customCta;

    // Record video
    const result = await recordScenario(scenario, {
      email: DEMO_EMAIL,
      password: DEMO_PASSWORD,
    });

    if (!result.success) {
      return NextResponse.json({ error: result.error || "Video üretimi başarısız" }, { status: 500 });
    }

    // Save to database as scheduled post
    if (clinicId && result.videoUrl) {
      await prisma.scheduledPost.create({
        data: {
          clinicId,
          type: "tweet",
          platform: "twitter",
          content: `${scenario.hookText}\n\n${scenario.ctaText}\n\n#pobyai #işletmeyönetimi`,
          imageUrl: result.videoUrl,
          scheduledAt: new Date(),
          status: "DRAFT",
          occasion: `Video: ${scenario.name}`,
          isAutoGenerated: true,
        },
      });
    }

    return NextResponse.json({
      success: true,
      videoUrl: result.videoUrl,
      frameCount: result.frameCount,
      scenario: scenario.name,
    });
  } catch (error) {
    console.error("Video generate error:", error);
    return NextResponse.json({ error: "Video üretimi başarısız" }, { status: 500 });
  }
}
